# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FmdData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('farm_condition', models.TextField()),
                ('bgp_requirements', models.TextField()),
                ('corrective_action', models.TextField()),
                ('observed', models.DateTimeField(auto_now_add=True)),
                ('hand_delivered', models.DateTimeField(auto_now_add=True, null=True)),
                ('corrected', models.DateTimeField(auto_now_add=True, null=True)),
                ('fmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmd.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
